name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
        - name: executing remote ssh commands using password
          uses: appleboy/ssh-action@v0.1.6
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.ROOT }}
            password: ${{ secrets.ROOTPASSWORD }}
            port: 22
            script: 
              scp -r ./server ${{ secrets.ROOT }}@${{ secrets.ID_ADDRESS }}:~/
              ssh ${{ secrets.ROOT }}@${{ secrets.ID_ADDRESS }} cd server; bash run.sh
