name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
        - name: Upload server
          run: 
            scp -r ./server ${{ secrets.ROOT }}@${{ secrets.ID_ADDRESS }}:~/
            ssh ${{ secrets.ROOT }}@${{ secrets.ID_ADDRESS }} cd server; bash run.sh
